//method_info {
//    u2             access_flags;
//    u2             name_index;
//    u2             descriptor_index;
//    u2             attributes_count;
//    attribute_info attributes[attributes_count];
//}

function MethodInfo(bytesArray, startByteIndex) {
    this.bytes = bytesArray;
    var accessFlags = getTwoBytes(bytesArray, startByteIndex);
    var nameIndex = getTwoBytes(bytesArray, startByteIndex + 2);
    var descriptorIndex = getTwoBytes(bytesArray, startByteIndex + 4);
    var attributesCount = getTwoBytes(bytesArray, startByteIndex + 6);
    var attributes = [];
    var attributesLength = 0;
    var arrayIndex = startByteIndex + 8;
    for(var i = 0; i < attributesCount; i++) {
        var attributeInfo = new AttributeInfo(bytesArray, arrayIndex);
        attributes.push(attributeInfo);
        attributesLength += attributeInfo.length();
        arrayIndex += attributeInfo.length();
    }

     this.getStartByteIndex = function() {
         return startByteIndex;
     }

     this. length = function() {
         return attributesLength + 8;
     }

     this.getEndByteIndex = function() {
         return this.getStartByteIndex() + this.length();
     }

     this.contains = function (index) {
         if(index >= this.getStartByteIndex() && index < this.getStartByteIndex() + this.length()) {
             return true;
         }
         else {
             return false;
         }
     }

    this.getCssClass = function() {
        return "method-info-section";
    }

     this.getBytecode = function (index, constants) {
        var descriptor = getDirectString(descriptorIndex, constants);
        var lookup = null;
        var rval = "Method: <br/>" +
        formatAsHexString(accessFlags) + " Access flags:" + formatAsBinaryString(accessFlags) + "</br>" +
        formatAsHexString(nameIndex) + " #" + nameIndex + " " + getDirectString(nameIndex, constants) + "<br/>" +
        formatAsHexString(descriptorIndex) + " #" + descriptorIndex + " " + descriptor + "<br/>" +
        formatAsHexString(attributesCount) + " Attributes count: " + attributesCount + "<br/>";
        for(var i = 0; i < attributes.length; i++) {
            var attribute = attributes[i];
            rval += attribute.getBytecode(startByteIndex, constants) + "<br/>";
        }

        rval +=
            "<table>" +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0001) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_PUBLIC	    </td><td class='access-table-mask'>0x0001</td><td>Declared public; may be accessed from outside its package." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0002) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_PRIVATE	    </td><td class='access-table-mask'>0x0002</td><td>Declared private; accessible only within the defining class." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0004) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_PROTECTED	</td><td class='access-table-mask'>0x0004</td><td>Declared protected; may be accessed within subclasses." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0008) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_STATIC	    </td><td class='access-table-mask'>0x0008</td><td>Declared static." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0010) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_FINAL	    </td><td class='access-table-mask'>0x0010</td><td>Declared final; must not be overridden (§5.4.5)." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0020) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_SYNCHRONIZED</td><td class='access-table-mask'>0x0040</td><td>Declared synchronized; invocation is wrapped by a monitor use." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0040) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_BRIDGE	    </td><td class='access-table-mask'>0x0080</td><td>A bridge method, generated by the compiler." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0080) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_VARARGS	    </td><td class='access-table-mask'>0x1000</td><td>Declared with variable number of arguments." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0100) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_NATIVE	    </td><td class='access-table-mask'>0x1000</td><td>Declared native; implemented in a language other than Java." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0400) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_ABSTRACT	</td><td class='access-table-mask'>0x1000</td><td>Declared abstract; no implementation is provided." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x0800) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_STRICT	    </td><td class='access-table-mask'>0x1000</td><td>Declared strictfp; floating-point mode is FP-strict." +
                "<tr><td class='access-table-mapped'></td><td class='access-table-desc " + ((accessFlags & 0x1000) != 0?"access-table-bold'":"access-table-dull'") + "'>ACC_SYNTHETIC	</td><td class='access-table-mask'>0x1000</td><td>Declared synthetic; not present in the source code." +
            "</table><br/>";

        return rval;
     }
}